version: "3.2"
services:
  mongo:
    image: mongo

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:alpine

  sql-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jajaja
      MYSQL_DATABASE: test_sql

  consul:
    image: consul
    environment:
      CONSUL_LOCAL_CONFIG: '{"disable_update_check": true}'
    command: agent -ui -server -bind 0.0.0.0 -client 0.0.0.0 -log-level warn -dev

  sdk-test:
    image: sendev/go
    build:
      context: ./docker
      dockerfile: Dockerfile-sdk
    volumes:
    - type: bind
      source: .
      target: /go/src/gitlab.sendo.vn/core/golang-sdk
    - /etc/localtime:/etc/localtime:ro
    working_dir: /go/src/gitlab.sendo.vn/core/golang-sdk
    command: go test ./tests -v
    depends_on:
    - mongo
    - redis
    - consul
    - rabbitmq
    - sql-mysql
    environment:
      SSD_URI: http://consul:8500
      REDIS_URI: redis://redis/0
      MGO_URI: mongodb://mongo/test
      AMQP_URI: amqp://rabbitmq

      TEST_SQL_USER: root
      TEST_SQL_PASS: jajaja
      TEST_SQL_HOST: sql-mysql
      TEST_SQL_DB: test_sql

  sdk-test-19:
    image: sendev/go:1.9
    build:
      context: ./docker
      dockerfile: Dockerfile-sdk
      args:
        gover: 1.9
    volumes:
    - type: bind
      source: .
      target: /go/src/gitlab.sendo.vn/core/golang-sdk
    - /etc/localtime:/etc/localtime:ro
    working_dir: /go/src/gitlab.sendo.vn/core/golang-sdk
    command: go test ./tests -v
    depends_on:
    - mongo
    - redis
    - consul
    - rabbitmq
    environment:
      SSD_URI: http://consul:8500
      REDIS_URI: redis://redis/0
      MGO_URI: mongodb://mongo/test
      AMQP_URI: amqp://rabbitmq

      TEST_SQL_USER: root
      TEST_SQL_PASS: jajaja
      TEST_SQL_HOST: sql-mysql
      TEST_SQL_DB: test_sql