// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/hashicorp/consul/api"
import mock "github.com/stretchr/testify/mock"

// Agent is an autogenerated mock type for the Agent type
type Agent struct {
	mock.Mock
}

// DeregisterService provides a mock function with given fields: _a0
func (_m *Agent) DeregisterService(_a0 string) {
	_m.Called(_a0)
}

// GetCheckIP provides a mock function with given fields:
func (_m *Agent) GetCheckIP() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetKVs provides a mock function with given fields:
func (_m *Agent) GetKVs() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// IsRunning provides a mock function with given fields:
func (_m *Agent) IsRunning() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RegisterService provides a mock function with given fields: _a0
func (_m *Agent) RegisterService(_a0 *api.AgentServiceRegistration) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*api.AgentServiceRegistration) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
