// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"

import server "gitlab.sendo.vn/core/golang-sdk/new/server"

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// AddHandler provides a mock function with given fields: _a0
func (_m *Server) AddHandler(_a0 func(*grpc.Server)) {
	_m.Called(_a0)
}

// AddOption provides a mock function with given fields: _a0
func (_m *Server) AddOption(_a0 grpc.ServerOption) {
	_m.Called(_a0)
}

// Configure provides a mock function with given fields:
func (_m *Server) Configure() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *Server) Get() *grpc.Server {
	ret := _m.Called()

	var r0 *grpc.Server
	if rf, ok := ret.Get(0).(func() *grpc.Server); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.Server)
		}
	}

	return r0
}

// GetConfig provides a mock function with given fields:
func (_m *Server) GetConfig() server.Config {
	ret := _m.Called()

	var r0 server.Config
	if rf, ok := ret.Get(0).(func() server.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(server.Config)
	}

	return r0
}

// InitFlags provides a mock function with given fields:
func (_m *Server) InitFlags() {
	_m.Called()
}

// Name provides a mock function with given fields:
func (_m *Server) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Reload provides a mock function with given fields: config
func (_m *Server) Reload(config server.Config) {
	_m.Called(config)
}

// Run provides a mock function with given fields:
func (_m *Server) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Server) Stop() <-chan bool {
	ret := _m.Called()

	var r0 <-chan bool
	if rf, ok := ret.Get(0).(func() <-chan bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bool)
		}
	}

	return r0
}

// URI provides a mock function with given fields:
func (_m *Server) URI() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
