// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mgo "github.com/globalsign/mgo"
import mock "github.com/stretchr/testify/mock"
import redis "github.com/gomodule/redigo/redis"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Mgo provides a mock function with given fields:
func (_m *Storage) Mgo() *mgo.Session {
	ret := _m.Called()

	var r0 *mgo.Session
	if rf, ok := ret.Get(0).(func() *mgo.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Session)
		}
	}

	return r0
}

// Redis provides a mock function with given fields:
func (_m *Storage) Redis() redis.Conn {
	ret := _m.Called()

	var r0 redis.Conn
	if rf, ok := ret.Get(0).(func() redis.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.Conn)
		}
	}

	return r0
}
