// Code generated by protoc-gen-sendo. DO NOT EDIT.
// Author: Viet Tran. Software Architect - DC1
// source: cabinets/cabinet/cabinet.proto

/*
Package cabinet is a generated protocol buffer package.

It is generated from these files:
	cabinets/cabinet/cabinet.proto

It has these top-level messages:
	GetRequest
	GetResponse
	SaveRequest
	SaveResponse
	ListRequest
	ListResponse
	ListResponseData
*/
package cabinet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "gitlab.sendo.vn/protobuf/internal-apis-go/cabinets"
import _ "gitlab.sendo.vn/protobuf/internal-apis-go/base"

import (
	context "context"
	sendo "gitlab.sendo.vn/core/golang-sdk/new"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// Client API for CabinetService service

type CabinetService interface {
	Save(sdCtx sendo.ServiceContext, ctx context.Context, in *SaveRequest) (*SaveResponse, error)
	//   rpc Delete(DeleteRequest) returns (DeleteResponse) {}
	//   rpc Edit(EditRequest) returns (EditResponse) {}
	// List cabinet by condition
	List(sdCtx sendo.ServiceContext, ctx context.Context, in *ListRequest) (*ListResponse, error)
	Get(sdCtx sendo.ServiceContext, ctx context.Context, in *GetRequest) (*GetResponse, error)
}

type sDCabinetServiceServer struct {
	ctx sendo.ServiceContext
	sv  CabinetService
}

func NewSDCabinetServiceServer(ctx sendo.ServiceContext, sv CabinetService) *sDCabinetServiceServer {
	return &sDCabinetServiceServer{
		sv:  sv,
		ctx: ctx,
	}
}

func (h *sDCabinetServiceServer) Save(ctx context.Context, in *SaveRequest) (*SaveResponse, error) {
	return h.sv.Save(h.ctx, ctx, in)
}

func (h *sDCabinetServiceServer) List(ctx context.Context, in *ListRequest) (*ListResponse, error) {
	return h.sv.List(h.ctx, ctx, in)
}

func (h *sDCabinetServiceServer) Get(ctx context.Context, in *GetRequest) (*GetResponse, error) {
	return h.sv.Get(h.ctx, ctx, in)
}

func AddCabinetServiceHandler(service sendo.Service, sv CabinetService) {
	service.Server().AddHandler(func(gRPC *grpc.Server) {
		RegisterCabinetServiceServer(gRPC, NewSDCabinetServiceServer(service, sv))
	})
}
