version: "3.2"

services:
{{- if .Resources.consul }}
  consul:
    image: consul
    environment:
      CONSUL_LOCAL_CONFIG: '{"disable_update_check": true}'
    command:
      agent -ui -server -bind 0.0.0.0 -client 0.0.0.0 -log-level warn -dev
{{- end }}

  {{- if .Resources.mgo }}

  mongo:
    image: mongo
  {{- end }}

  {{- if .Resources.redis }}

  redis:
    image: redis:alpine
  {{- end }}

  {{- if .Resources.amqp }}

  rabbitmq:
    image: rabbitmq:management-alpine
  {{- end }}

  myapp:
    image: sendev/go
    volumes:
    - type: bind
      source: .
      target: /go/src/{{ .ImportPath }}
    - /etc/localtime:/etc/localtime:ro
    working_dir: /go/src/{{ .ImportPath }}
{{- if .Resources.consul }}
    links:
    - consul:myconsul
{{- end }}
    environment:
{{- if .Resources.consul }}
      SSD_URI: http://myconsul:8500
{{- end }}
      LOGLEVEL: debug
      PORT: 10000

      {{- if .Resources.redis }}
      REDIS_URI: redis://redis/0
      REDIS_POOL_MAX_IDLE: 20
      {{- end }}
      {{- if .Resources.mgo }}
      MGO_URI: mongodb://mongo/test
      {{- end }}
      {{- if .Resources.amqp }}
      AMQP_URI: amqp://rabbitmq
      {{- end }}
{{- if or .Resources.redis .Resources.mgo .Resources.amqp .Resources.consul}}
    depends_on:
    {{- if .Resources.redis }}
    - redis
    {{- end }}
    {{- if .Resources.mgo }}
    - mongo
    {{- end }}
    {{- if .Resources.amqp }}
    - rabbitmq
    {{- end }}
    {{- if .Resources.consul }}
    - consul
    {{- end }}
{{- end }}
    command: run
