# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

## Uncomment following lines if need use custom version of internal-apis-go
#required = [
#  "google.golang.org/genproto/googleapis/api/annotations",
#  "github.com/gogo/protobuf/proto", "github.com/gogo/protobuf/types"
#]
#ignored = ["gitlab.sendo.vn/protobuf/internal-apis-go/*"]

{{- if .Resources.redis }}

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = ">=v2.0.0"
{{- end }}

[prune]
  go-tests = true
