// Code generated by protoc-gen-sendo. DO NOT EDIT.
// Author: Viet Tran. Software Architect - DC1
// source: cabinets/category/category.proto

/*
Package category is a generated protocol buffer package.

It is generated from these files:
	cabinets/category/category.proto

It has these top-level messages:
	ListRequest
	ListResponse
	SimpleCate
	GetRequest
	GetResponse
	Cate
	CateChild
*/
package category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "gitlab.sendo.vn/protobuf/internal-apis-go/cabinets"

import (
	context "context"
	sendo "gitlab.sendo.vn/core/golang-sdk/new"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// Client API for CategoryService service

type CategoryService interface {
	// Get list of cate 1
	List(sdCtx sendo.ServiceContext, ctx context.Context, in *ListRequest) (*ListResponse, error)
	// Get single category with its parent and children
	Get(sdCtx sendo.ServiceContext, ctx context.Context, in *GetRequest) (*GetResponse, error)
}

type sDCategoryServiceServer struct {
	ctx sendo.ServiceContext
	sv  CategoryService
}

func NewSDCategoryServiceServer(ctx sendo.ServiceContext, sv CategoryService) *sDCategoryServiceServer {
	return &sDCategoryServiceServer{
		sv:  sv,
		ctx: ctx,
	}
}

func (h *sDCategoryServiceServer) List(ctx context.Context, in *ListRequest) (*ListResponse, error) {
	return h.sv.List(h.ctx, ctx, in)
}

func (h *sDCategoryServiceServer) Get(ctx context.Context, in *GetRequest) (*GetResponse, error) {
	return h.sv.Get(h.ctx, ctx, in)
}

func AddCategoryServiceHandler(service sendo.Service, sv CategoryService) {
	service.Server().AddHandler(func(gRPC *grpc.Server) {
		RegisterCategoryServiceServer(gRPC, NewSDCategoryServiceServer(service, sv))
	})
}
