// Code generated by protoc-gen-sendo. DO NOT EDIT.
// Author: Viet Tran. Software Architect - DC1
// source: seller/store/store.proto

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	seller/store/store.proto

It has these top-level messages:
	AlowCheckOrderRes
	MenuRep
	MenuRes
	SendoMenu
	RegShopStep2Req
	RegShopStep3Req
	RegShopStep4Req
	RegShopStep5Req
	RegShopStep6Req
	RegShopStep7Req
	FileUploadDto
	UserContextDtoRes
	UserContextDto
	CheckExistsUsershopWithoutAuthenReq
	CheckExistsUsershopWithoutAuthenRes
	CheckRegisterAndSendOtpRes
	ApiRes
	RegionRes
	Region
	DistrictRes
	District
	DistrictWardRes
	DistrictWard
	RegionReq
	RegionWHReq
	DistrictReq
	DistrictWHReq
	DistrictWardReq
	ShopInfoReq
	ChangeEmailReq
	PhoneShopReq
	UpdateShopDetailReq
	ShopDtoRes
	ShopDto
	ShopDetailReq
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "context"
	sendo "gitlab.sendo.vn/core/golang-sdk/new"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// Client API for StoreService service

type StoreService interface {
	// register shop
	// CheckExistsUsershopWithoutAuthen
	CheckExistsUsershopWithoutAuthen(sdCtx sendo.ServiceContext, ctx context.Context, in *CheckExistsUsershopWithoutAuthenReq) (*CheckExistsUsershopWithoutAuthenRes, error)
	// CheckRegisterAndSendOtp
	// rpc CheckRegisterAndSendOtp (CheckRegisterAndSendOtpReg) returns (CheckRegisterAndSendOtpRes) {}
	RegShopStep2(sdCtx sendo.ServiceContext, ctx context.Context, in *RegShopStep2Req) (*UserContextDtoRes, error)
	RegShopStep3(sdCtx sendo.ServiceContext, ctx context.Context, in *RegShopStep3Req) (*UserContextDtoRes, error)
	RegShopStep4(sdCtx sendo.ServiceContext, ctx context.Context, in *RegShopStep4Req) (*UserContextDtoRes, error)
	RegShopStep5(sdCtx sendo.ServiceContext, ctx context.Context, in *RegShopStep5Req) (*UserContextDtoRes, error)
	RegShopStep6(sdCtx sendo.ServiceContext, ctx context.Context, in *RegShopStep6Req) (*UserContextDtoRes, error)
	RegShopStep7(sdCtx sendo.ServiceContext, ctx context.Context, in *RegShopStep7Req) (*UserContextDtoRes, error)
	GetRegions(sdCtx sendo.ServiceContext, ctx context.Context, in *RegionReq) (*RegionRes, error)
	GetRegionWHs(sdCtx sendo.ServiceContext, ctx context.Context, in *RegionWHReq) (*RegionRes, error)
	GetDistricts(sdCtx sendo.ServiceContext, ctx context.Context, in *DistrictReq) (*DistrictRes, error)
	GetDistrictWHs(sdCtx sendo.ServiceContext, ctx context.Context, in *DistrictWHReq) (*DistrictRes, error)
	GetDistrictWards(sdCtx sendo.ServiceContext, ctx context.Context, in *DistrictWardReq) (*DistrictWardRes, error)
	GetShopInfo(sdCtx sendo.ServiceContext, ctx context.Context, in *ShopInfoReq) (*UserContextDtoRes, error)
	ReqChangeEmail(sdCtx sendo.ServiceContext, ctx context.Context, in *ChangeEmailReq) (*ApiRes, error)
	UpdateEmailShop(sdCtx sendo.ServiceContext, ctx context.Context, in *ChangeEmailReq) (*ApiRes, error)
	ReqChangePhone(sdCtx sendo.ServiceContext, ctx context.Context, in *PhoneShopReq) (*ApiRes, error)
	UpdatePhoneShop(sdCtx sendo.ServiceContext, ctx context.Context, in *PhoneShopReq) (*ApiRes, error)
	GetShopDetail(sdCtx sendo.ServiceContext, ctx context.Context, in *ShopDetailReq) (*ShopDtoRes, error)
	UpdateShopDetail(sdCtx sendo.ServiceContext, ctx context.Context, in *UpdateShopDetailReq) (*ShopDtoRes, error)
	GetMenu(sdCtx sendo.ServiceContext, ctx context.Context, in *MenuRes) (*MenuRep, error)
	UpdateAlowCheckOrder(sdCtx sendo.ServiceContext, ctx context.Context, in *AlowCheckOrderRes) (*ApiRes, error)
}

type sDStoreServiceServer struct {
	ctx sendo.ServiceContext
	sv  StoreService
}

func NewSDStoreServiceServer(ctx sendo.ServiceContext, sv StoreService) *sDStoreServiceServer {
	return &sDStoreServiceServer{
		sv:  sv,
		ctx: ctx,
	}
}

func (h *sDStoreServiceServer) CheckExistsUsershopWithoutAuthen(ctx context.Context, in *CheckExistsUsershopWithoutAuthenReq) (*CheckExistsUsershopWithoutAuthenRes, error) {
	return h.sv.CheckExistsUsershopWithoutAuthen(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) RegShopStep2(ctx context.Context, in *RegShopStep2Req) (*UserContextDtoRes, error) {
	return h.sv.RegShopStep2(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) RegShopStep3(ctx context.Context, in *RegShopStep3Req) (*UserContextDtoRes, error) {
	return h.sv.RegShopStep3(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) RegShopStep4(ctx context.Context, in *RegShopStep4Req) (*UserContextDtoRes, error) {
	return h.sv.RegShopStep4(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) RegShopStep5(ctx context.Context, in *RegShopStep5Req) (*UserContextDtoRes, error) {
	return h.sv.RegShopStep5(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) RegShopStep6(ctx context.Context, in *RegShopStep6Req) (*UserContextDtoRes, error) {
	return h.sv.RegShopStep6(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) RegShopStep7(ctx context.Context, in *RegShopStep7Req) (*UserContextDtoRes, error) {
	return h.sv.RegShopStep7(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetRegions(ctx context.Context, in *RegionReq) (*RegionRes, error) {
	return h.sv.GetRegions(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetRegionWHs(ctx context.Context, in *RegionWHReq) (*RegionRes, error) {
	return h.sv.GetRegionWHs(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetDistricts(ctx context.Context, in *DistrictReq) (*DistrictRes, error) {
	return h.sv.GetDistricts(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetDistrictWHs(ctx context.Context, in *DistrictWHReq) (*DistrictRes, error) {
	return h.sv.GetDistrictWHs(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetDistrictWards(ctx context.Context, in *DistrictWardReq) (*DistrictWardRes, error) {
	return h.sv.GetDistrictWards(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetShopInfo(ctx context.Context, in *ShopInfoReq) (*UserContextDtoRes, error) {
	return h.sv.GetShopInfo(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) ReqChangeEmail(ctx context.Context, in *ChangeEmailReq) (*ApiRes, error) {
	return h.sv.ReqChangeEmail(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) UpdateEmailShop(ctx context.Context, in *ChangeEmailReq) (*ApiRes, error) {
	return h.sv.UpdateEmailShop(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) ReqChangePhone(ctx context.Context, in *PhoneShopReq) (*ApiRes, error) {
	return h.sv.ReqChangePhone(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) UpdatePhoneShop(ctx context.Context, in *PhoneShopReq) (*ApiRes, error) {
	return h.sv.UpdatePhoneShop(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetShopDetail(ctx context.Context, in *ShopDetailReq) (*ShopDtoRes, error) {
	return h.sv.GetShopDetail(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) UpdateShopDetail(ctx context.Context, in *UpdateShopDetailReq) (*ShopDtoRes, error) {
	return h.sv.UpdateShopDetail(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) GetMenu(ctx context.Context, in *MenuRes) (*MenuRep, error) {
	return h.sv.GetMenu(h.ctx, ctx, in)
}

func (h *sDStoreServiceServer) UpdateAlowCheckOrder(ctx context.Context, in *AlowCheckOrderRes) (*ApiRes, error) {
	return h.sv.UpdateAlowCheckOrder(h.ctx, ctx, in)
}

func AddStoreServiceHandler(service sendo.Service, sv StoreService) {
	service.Server().AddHandler(func(gRPC *grpc.Server) {
		RegisterStoreServiceServer(gRPC, NewSDStoreServiceServer(service, sv))
	})
}
